---
title: "ROSE Table for Patient Data Simulation"
author: "Jazmin M. Trejo and Nicole Salani"
date: '2022-04-25'
header-includes:
  - \usepackage{float}
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyr)  # for certain data transformation
library(dplyr) # for pipes
library(tidyverse) # data manipulation, plotting with ggplot2
library(readxl)
library(gmodels) # cross tabulation
library(Hmisc) # more data manipulation
library(lubridate) # date manipulation 
library(reshape2)
library(gtsummary)

# install java later
library(rJava)
#consider expanding working memory when working with excel files 
options(java.parameters = "-Xmx8000m")
library(xlsx) # if we need to export an excel and format accordingly

library(openxlsx)


# randomly create IDs to be selected in data manipulation 
idmaker <- function(x){
    max.val = x*100
    count <- nchar(as.character(max.val))                       # find out how many 'numbers' each ID will have after the letter
    size <- paste("%0",count,"d",sep="")                        # set the variable to be fed into 'sprintf' to ensure we have leading 0's
    lets <- toupper(sample(letters,x, replace=T))               # randomising the letters 
    nums <- sprintf(size,sample(1:max.val)[1:x])                # randominsing the numbers, and ensuing they all have the same number of characters
    ids <- paste(lets,nums,sep="")                              # joining them together
  return(ids)
}

```





```{r hispanic patients, echo=FALSE}
### Hispanics Patients Subsample data
## 	Hispanic Patients*	48 (10.2%)
hispanic_sample <- 48
Hispanic <- tibble::tibble(Ethnicity = rep(c("Hispanic"),  hispanic_sample))


set.seed(10001)

Hispanic <- Hispanic %>% 
  
  mutate(  # Age+	54.4 (15.4)
         Age = rnorm(hispanic_sample, mean = 54.4, sd =15.4),
         
          # Male	25 (52.1%)
          Male = rbinom(hispanic_sample, 1, p = 25/hispanic_sample), 
         
          # Tobacco use	 
          #   Former smoker	8 (16.7%)
          Former.smoker = rbinom(hispanic_sample, 1, p = 8/hispanic_sample),
         
          #   Current smoker	9 (18.8%)
         Current.smoker = rbinom(hispanic_sample, 1, p = 9/hispanic_sample),
          
          # Comorbidities	---------- 
          #   Leukemia or lymphoma	3 (6.3%)
         Leukemia.or.lymphoma = rbinom(hispanic_sample, 1, p = 3/hispanic_sample),
         
          #   Metastatic cancer	1 (2.1%)
         Metastatic.cancer	 = rbinom(hispanic_sample, 1, p = 1/hispanic_sample),
         
          #   Immune suppression	10 (20.8%)
          Immune.suppression = rbinom(hispanic_sample, 1, p = 10/hispanic_sample),
         
          #   Cirrhosis	8 (16.7%)
         Cirrhosis =  rbinom(hispanic_sample, 1, p = 8/hispanic_sample),
         
          #   Diabetes	17 (35.4%)
          Diabetes = rbinom(hispanic_sample, 1, p = 17/hispanic_sample),
         
          #   Hypertension	22 (45.8%)
          Hypertension = rbinom(hispanic_sample, 1, p = 22/hispanic_sample),
          
          #   Myocardial infarction	3 (6.3%)
          Myocardial.infarction = rbinom(hispanic_sample, 1, p = 3/hispanic_sample),
          
          #   Heart failure	3 (6.3%)
           Heart.failure	= rbinom(hispanic_sample, 1, p = 3/hispanic_sample),
          
          #   Stroke	4 (8.3%)
           Stroke = rbinom(hispanic_sample, 1, p = 4/hispanic_sample),
          
          #   Dementia	5 (10.4%)
           Dementia = rbinom(hispanic_sample, 1, p = 5/hispanic_sample),
          
          #   Chronic lung disease	5 (10.4%)
           Chronic.lung.disease = rbinom(hispanic_sample, 1, p = 5/hispanic_sample),
          
          #   Dialysis	2 (4.2%)
           Dialysis = rbinom(hispanic_sample, 1, p = 2/hispanic_sample),
         
          # Body mass index+	29.5 (8.2)
          Body.mass.index = rnorm(hispanic_sample, mean = 29.5, sd = 8.2),
         
          # Baseline P/F ratio+	114.4 (35.9)
          Baseline.PF.ratio = rnorm(hispanic_sample, mean = 114.4, sd = 35.9),
         
          # Neuromuscular Blockade	17 (35.4%)
         Neuromuscular.Blockade = rbinom(hispanic_sample, 1, p = 17/hispanic_sample),
         
          # Deep Sedation (days 0 to 4):-------------
         
          #   Received deep sedation at any time	45 (93.8%)
         Received.deep.sedation = rbinom(hispanic_sample, 1, p = 45/hispanic_sample),
          
          #   Proportion of days deeply sedated+	85.8 (27.4)
          Prop.days.deeply.sedated = rnorm(hispanic_sample, mean = 85.8, sd = 27.4),
         
          # Benzodiazepines (days 0 to 4):-------------
         
          #   Received benzodiazepines at any time;	23 (47.9%)
          Received.benzodiazepines = rbinom(hispanic_sample, 1, p = 23/hispanic_sample),
          
          #   Proportion of days receiving benzodiazepines+	; 33.4 (40.7)
           Prop.days.receiving.benzodiazepines = rnorm(hispanic_sample, mean = 33.4, sd = 40.7),
         
          # SOFA score (Neuro excluded)+;	10.3 (3.2)
          SOFA.score.Neuro.excl = rnorm(hispanic_sample, mean = 10.3, sd = 3.2),
         
          # APACHE score (All categories)+ ;	115.5 (32.0)
           APACHE.score.All.categ = rnorm(hispanic_sample, mean = 115.5, sd = 32.0),
         
          # APACHE score (GCS excluded)+;	84.9 (24.6)
          APACHE.score.GCS.excl = rnorm(hispanic_sample, mean = 84.9, sd =24.6),
         
          # pH+	; 7.30 (0.11)
          pH = rnorm(hispanic_sample, mean = 7.295, sd = 0.113),
         
          # Proportion of days 0 to 4 ventilated+	; 93.9 (15.0)
          Prop.days.0to4.ventilated = rnorm(hispanic_sample, mean = 93.9, sd =15.0),
         
          # Died within 90 Days	; 25 (52.1%)
         Died.within.90.Days = rbinom(hispanic_sample, 1, p = 25/hispanic_sample) )
  



```





```{r white patients data, echo=FALSE}
### White Patients Subsample data
## White Patients*	302 (64.1%) 
white_sample <- 302
White <- tibble::tibble(Ethnicity=  rep("White", white_sample))



set.seed(10001)

White <- White %>% 
  mutate( # Age+	55.5 (16.4)
        Age = rnorm(white_sample, mean = 55.5, sd = 16.4),

        # Male	158 (52.3%)
        Male = rbinom(white_sample, 1, p = 158/white_sample),
        
        # Tobacco use:---------
        #   Former smoker	89 (29.5%)
        Former.smoker = rbinom(white_sample, 1, p = 89/white_sample),
        
        #   Current smoker	84 (27.8%)
        Current.smoker = rbinom(white_sample, 1, p =  84/white_sample), 

        # Comorbidities:------------
        #   Leukemia or lymphoma	13 (4.3%)
        Leukemia.or.lymphoma = rbinom(white_sample, 1, p = 13/white_sample),


        #   Metastatic cancer	15 (5.0%)
       Metastatic.cancer = rbinom(white_sample, 1, p = 15/white_sample),

        #   Immune suppression	53 (17.5%)
        Immune.suppression = rbinom(white_sample, 1, p = 53/white_sample),
        
        #   Cirrhosis	24 (7.9%)
        Cirrhosis= rbinom(white_sample, 1, p = 24/white_sample),

        #   Diabetes	81 (26.8%)
        Diabetes = rbinom(white_sample, 1, p = 81/white_sample),

        #   Hypertension	142 (47.0%)
        Hypertension = rbinom(white_sample, 1, p = 142/white_sample),

        #   Myocardial infarction	18 (6.0%)
        Myocardial.infarction = rbinom(white_sample, 1, p = 18/white_sample),
       
       
        #   Heart failure	16 (5.3%)
        Heart.failure = rbinom(white_sample, 1, p = 16/white_sample),
        
        #   Stroke	9 (3.0%)
        Stroke = rbinom(white_sample, 1, p = 9/white_sample), 
       
        #   Dementia	6 (2.0%)
        Dementia = rbinom(white_sample, 1, p = 6/white_sample),
       
       
        #   Chronic lung disease	61 (20.2%)
         Chronic.lung.disease = rbinom(white_sample, 1, p = 61/white_sample),
       
        #   Dialysis	6 (2.0%)
        Dialysis = rbinom(white_sample, 1, p = 6/white_sample),
       
       # Body mass index+	32.7 (9.3)
        Body.mass.index = rnorm(white_sample, mean = 32.7, sd = 9.3),

        # Baseline P/F ratio+	116.4 (39.2)
       Baseline.PF.ratio = rnorm(white_sample, mean = 116.4, sd = 39.2),

      # Neuromuscular Blockade	75 (24.8%)
        Neuromuscular.Blockade =  rbinom(white_sample,  1, p = 75/white_sample),
      
        # Deep Sedation (days 0 to 4):----------
        
        # Received deep sedation at any time	263 (87.1%)
        Received.deep.sedation =  rbinom(white_sample,  1, p = 263/white_sample),
        
        #   Proportion of days deeply sedated+	64.2 (35.9)
        Prop.days.deeply.sedated = rnorm(white_sample, mean = 64.2, sd = 35.9),
        
        # Benzodiazepines (days 0 to 4):---------- 
        # Received benzodiazepines at any time;	154 (51.0%)
        Received.benzodiazepines =  rbinom(white_sample,  1, p = 154/white_sample),
      
        # Proportion of days receiving benzodiazepines+	;  32.5 (38.9) MVP Adjusted ; from workbook: Original 30.3±36.7
         Prop.days.receiving.benzodiazepines = rnorm(white_sample, mean = 32.5, sd = 38.9),
      
        # SOFA score (Neuro excluded)+ ; 8.7 (3.3)
        SOFA.score.Neuro.excl = rnorm(white_sample, mean = 8.7, sd = 3.3),
        
        # APACHE score (All categories)+ ; 105.7 (29.8)
        APACHE.score.All.categ = rnorm(white_sample, mean = 105.7, sd = 29.8),
      
        # APACHE score (GCS excluded)+ ; 77.1 (22.1)
        APACHE.score.GCS.excl = rnorm(white_sample, mean = 77.1, sd = 22.1),
      
        # pH+	; 7.32 (0.10)
        pH = rnorm(white_sample, mean = 7.319, sd = 0.096),
      
        # Proportion of days 0 to 4 ventilated+	; 91.7 (17.0)
        Prop.days.0to4.ventilated =  rnorm(white_sample,  mean = 91.7, sd = 17.0),
      
        # Died within 90 Days	; 125 (41.4%)
      Died.within.90.Days	 =  rbinom(white_sample,  1, p = 125/white_sample)
      )





```





```{r black patients data, echo=FALSE}
### Black Patients Subsample data
# Black patients 70 (14.9%)
black_sample <- 70
Black <- tibble::tibble(Ethnicity=  rep("Black", black_sample))



set.seed(10001)

Black <- Black %>% 
  mutate( # Age+	53.2 (14.9)
        Age = rnorm(black_sample, mean = 53.2, sd = 14.9),
        
        #  Male	39 (55.7%)
        Male = rbinom(black_sample, 1, p = 39/black_sample),

        # Tobacco use	 ----------
        # Former smoker	11 (15.7%)
        Former.smoker = rbinom(black_sample, 1, p = 11/black_sample),
        
        # Current smoker	21 (30.0%)
        Current.smoker = rbinom(black_sample, 1, p =  21/black_sample), 

        # Comorbidities	--------------

        # Leukemia or lymphoma	3 (4.3%)
        Leukemia.or.lymphoma = rbinom(black_sample, 1, p = 3/black_sample),
        
        # Metastatic cancer	3 (4.3%)
        Metastatic.cancer = rbinom(black_sample, 1, p = 3/black_sample),
        
        # Immune suppression	10 (14.3%)
        Immune.suppression = rbinom(black_sample, 1, p = 10/black_sample),
        
        # Cirrhosis	5 (7.1%)
        Cirrhosis= rbinom(black_sample, 1, p = 5/black_sample),
        
        # Diabetes	23 (32.9%)
        Diabetes = rbinom(black_sample, 1, p = 23/black_sample),
        
        #  Hypertension	37 (52.9%)
        Hypertension = rbinom(black_sample, 1, p = 37/black_sample),
        
        
        # Myocardial infarction	4 (5.7%)
        Myocardial.infarction = rbinom(black_sample, 1, p = 4/black_sample),
         
        # Heart failure	10 (14.3%)
        Heart.failure = rbinom(black_sample, 1, p = 10/black_sample),
        
        # Stroke	4 (5.7%)
        Stroke = rbinom(black_sample, 1, p = 4/black_sample), 
        
        # Dementia	2 (2.9%)
        Dementia = rbinom(black_sample, 1, p = 2/black_sample),

        # Chronic lung disease	9 (12.9%)
        Chronic.lung.disease = rbinom(black_sample, 1, p = 9/black_sample),
        
        # Dialysis	6 (8.6%)
        Dialysis = rbinom(black_sample, 1, p = 6/black_sample),
        
        # Body mass index+	30.2 (9.2)
        Body.mass.index = rnorm(black_sample, mean = 30.2, sd = 9.2),
        
        #  Baseline P/F ratio+	105.2 (36.9)
        Baseline.PF.ratio = rnorm(black_sample, mean = 105.2, sd = 36.9),
        
        # Neuromuscular Blockade	15 (21.4%)
        Neuromuscular.Blockade =  rbinom(black_sample,  1, p = 15/black_sample),
        
        # Deep Sedation (days 0 to 4)	-------
        #   Received deep sedation at any time	63 (90.0%)
         Received.deep.sedation =  rbinom(black_sample,  1, p = 63/black_sample),
        
        #   Proportion of days deeply sedated+	61.4 (33.0)
        Prop.days.deeply.sedated = rnorm(black_sample, mean = 61.4, sd = 33.0),
        
        # Benzodiazepines (days 0 to 4)	 -----------
        
        #   Received benzodiazepines  at any time:	27 (38.6%)
        Received.benzodiazepines =  rbinom(black_sample,  1, p = 27/black_sample),
        
        #   Proportion of days receiving benzodiazepines+	21.0 (32.4)
         Prop.days.receiving.benzodiazepines = rnorm(black_sample, mean = 21.0 , sd = 32.4 ),
        
        # SOFA score (Neuro excluded)+	9.3 (3.4)
        SOFA.score.Neuro.excl = rnorm(black_sample, mean = 9.3, sd = 3.4),
      
        # APACHE score (All categories)+	106.0 (26.7)
         APACHE.score.All.categ = rnorm(black_sample, mean = 106.0, sd = 26.7),
        
        # APACHE score (GCS excluded)+	78.9 (21.0)
        APACHE.score.GCS.excl= rnorm(black_sample, mean = 78.9, sd = 21.0),
        
        # pH+	7.331 (0.096)
        pH = rnorm(black_sample, mean = 7.331, sd = 0.096),
        
        # Proportion of days 0 to 4 ventilated+	92.4 (15.3)
        Prop.days.0to4.ventilated = rnorm(black_sample, mean = 92.4, sd = 15.3),
        
        # Died within 90 Days	25 (35.7%)
        Died.within.90.Days =  rbinom(black_sample,  1, p = 25/black_sample),
        
        )





```







```{r other patients data, echo=FALSE}
### Other Patients Subsample data

 # Other patients; 51 (10.8%)
other_sample <- 51 
Other <- tibble::tibble(Ethnicity=  rep("Other", other_sample))

set.seed(10001)

Other <- Other %>% 
   mutate( # Age 53.9 (15.6)
          Age = rnorm(other_sample, mean = 53.9, sd = 15.6),
          
          # Male 27 (52.9%)
          Male = rbinom(other_sample, 1, p = 27/other_sample),
          
          # Tobacco use	 ----------
          # Former smoker 17 (33.3%)
          Former.smoker = rbinom(other_sample, 1, p = 17/other_sample),
          
          # Current smoker 11 (21.6%)
          Current.smoker = rbinom(other_sample, 1, p =  11/other_sample), 
          
          # Comorbidities	--------------
          # Leukemia or lymphoma: 1 (2.0%)
          Leukemia.or.lymphoma = rbinom(other_sample, 1, p = 1/other_sample),
          
          # Metastatic cancer : 3 (5.9%)
          Metastatic.cancer = rbinom(other_sample, 1, p = 3/other_sample),
          
          # Immune suppression: 6 (11.8%)
          Immune.suppression = rbinom(other_sample, 1, p = 6/other_sample),
          
          # Cirrhosis: 3 (5.9%)
          Cirrhosis= rbinom(other_sample, 1, p = 3/other_sample),
          
          # Diabetes: 16 (31.4%)
          Diabetes = rbinom(other_sample, 1, p = 16/other_sample),
          
          # Hypertension; 19 (37.3%)
          Hypertension = rbinom(other_sample, 1, p = 19/other_sample),
          
          
          # Myocardial infarction; 6 (11.8%)
          Myocardial.infarction = rbinom(other_sample, 1, p = 6/other_sample),
           
          #  Heart failure; 2 (3.9%)
          Heart.failure = rbinom(other_sample, 1, p = 2/other_sample),
          
          # Stroke; 2 (3.9%)
          Stroke = rbinom(other_sample, 1, p = 2/other_sample), 
          
          # Dementia ; 2 (2.0%)
          Dementia = rbinom(other_sample, 1, p = 1/other_sample),
          
          # Chronic lung disease ; 11 (21.6%)
          Chronic.lung.disease = rbinom(other_sample, 1, p = 11/other_sample),
          
          # Dialysis; 4 (7.8%)
          Dialysis = rbinom(other_sample, 1, p = 4/51),
          
          # Body mass index+ : 28.3 (7.3)
          Body.mass.index = rnorm(other_sample, mean = 28.3, sd = 7.3),
          
          # Baseline P/F ratio+ : 111.9 (39.9)
          Baseline.PF.ratio = rnorm(other_sample, mean = 111.9, sd = 39.9),
          
          # Neuromuscular Blockade ; 16 (31.4%)
          Neuromuscular.Blockade =  rbinom(other_sample,  1, p = 16/other_sample),
          
          #Deep Sedation (days 0 to 4); ------------
          # Received deep sedation at any time ; 48 (94.1%)
           Received.deep.sedation  =  rbinom(other_sample,  1, p = 48/other_sample),
          
          # Proportion of days deeply sedated ; 78.5 (29.9)
          Prop.days.deeply.sedated = rnorm(other_sample, mean = 78.5, sd = 29.9),
          
          ## Benzodiazepines (days 0 to 4); ------------
          
          # Received benzodiazepines at any time ; 21 (41.2%)
           Received.benzodiazepines =  rbinom(other_sample,  1, p = 21/other_sample),
          
          # Proportion of days receiving benzodiazepines+ ; 27.6 (37.8)
          Prop.days.receiving.benzodiazepines = rnorm(other_sample, mean = 27.6, sd = 37.8),
          
          # SOFA score (Neuro excluded)+ ;  9.8 (3.8)
           SOFA.score.Neuro.excl = rnorm(other_sample, mean = 9.8, sd = 3.8),
          
          # APACHE score (All categories)+ : 107.2 (30.0)
          APACHE.score.All.categ = rnorm(other_sample, mean = 107.2, sd = 30.0),
          
          # APACHE score (GCS excluded)+ : 78.9 (21.5)
          APACHE.score.GCS.excl = rnorm(other_sample, mean = 78.9, sd = 21.5),
          
          # pH+: 7.319 (0.108)
          pH = rnorm(other_sample, mean = 7.319, sd = 0.108),
          
          # Proportion of days 0 to 4 ventilated+ : 88.4 (19.9)
          
          Prop.days.0to4.ventilated= rnorm(other_sample, mean = 88.4, sd = 19.9),
          
          # Died within 90 Days : 21 (41.2%) 
          Died.within.90.Days = rbinom(other_sample,  1, p = 21/other_sample)
          )






```


### Data Simulation Process

The data is simulated using R software based on summary statistics from *Table 1.  Patient characteristics by ethnicity or race* in the clinical trial manuscript.

The process is as follows :

1. Generate patient data for each ethnic or race group;
2. Then merge all ethnic or race group subsample data into one large dataset. 



```{r stack up subsample datasets, echo=FALSE, fig.align='center', warning=FALSE, message=FALSE}
## Stack-up datasets
patients_data <- rbind(Hispanic, White, Black, Other)




as_kable_extra_base <- patients_data %>%
  tbl_summary(
    by = Ethnicity,
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n} ({p}%)"),
    digits = all_continuous() ~ 2) %>% 
  add_overall() %>%
modify_header(label ~ "") %>%
 modify_footnote(
    all_stat_cols() ~ "Mean (SD) or N (%).  Data is Simulated for the 471 patients for whom complete sedation data were available.") %>%
  modify_caption("Table 1. Patient characteristics by ethnicity or race")


as_kable_extra_ex1_pdf <-
  as_kable_extra_base %>%
  as_kable_extra(booktabs = TRUE,  linesep = "") %>%
  kableExtra::kable_styling(
    latex_options = c("striped", "scale_down"),
    stripe_color = "gray!15"
  )

as_kable_extra_ex1_pdf

```



```{r export workbook, eval=FALSE, echo = FALSE}
### export workbook
write.xlsx(patients_data, "ROSE Simulated Data Tables.xlsx", sheetName = "Table1 Demographics (N=471)", append=FALSE)

```




```{r patient by day status, eval=FALSE, echo=FALSE}
## Patient by day status
days <- 5
patients_by_day <- tibble::tibble(patient_ID = rep(patients_data$patient.ID, days),
                                  Day = rep(0:4, each = 1, times = total_sample) )


## Deceased
# Day 0 : 7,  Day 1 : 39,  Day 2 : 56,  Day 3 : 69,  Day 4 : 80
deceased_n <- 7 + 39 + 56 + 69 + 80

patients_by_day <- patients_by_day %>% 
  mutate(Deceased = case_when()
         )

# # Sedation  Status Unknown
# Day 0 : 19,  Day 1 : 9, Day 2 : 11,  Day 3 : 11,  Day 4 : 10
sed_unknown_n <- 19 + 9 + 11 + 11 + 10

## Deeply Sedated
# Day 0 : 345 ,  Day 1 : 314,  Day 2 : 258,   Day 3 : 229,  Day 4 : 203
sed_deep_n <- 34 + 314 + 258 + 229 + 203

## Not Deeply Sedated
# Day 0 : 133,  Day 1 : 128,  Day 2 : 126,   Day 3 : 111,  Day 4 : 91
sed_notdeep_n <- 133 + 128 + 126 + 111 + 91

## Extubated
# Day 0 : 1,   Day 1 : 15,  Day 2 : 54,   Day 3 : 85,  Day 4 : 121





```




```{r ignore, eval=FALSE, echo=FALSE}
set.seed(10001)
total_sample <- 471
patients_data <- patients_data %>% mutate(patient.ID = idmaker(total_sample)) %>%
  select(patient.ID,
        Ethnicity,
        Age,
        Male,
        Former.smoker,
        Current.smoker, 
        Leukemia.or.lymphoma,
        Metastatic.cancer,
        Immune.suppression,
        Cirrhosis,
        Diabetes,
        Hypertension,
        Myocardial.infarction,
        Heart.failure,
        Stroke,
        Dementia,
        Chronic.lung.disease,
        Dialysis,
        Body.mass.index,
        Baseline.PF.ratio,
        Neuromuscular.Blockade)
```

